### ISSUE TITLE
Can you provide the code for Spatial-temporal feature extraction?

### ISSUE THREAD

**Issue by nextDeve** [ICLab4DL/GGN#1]
The Spatial-temporal feature extraction is not provided in your project.

**Comment by zhengdaoli** [comment]
1. First, the preprocess is the same as: https://github.com/IBM/seizure-type-classification-tuh, after that, you generated fft_seizures_wl1_ws_0.25_sf_250_fft_min_1_fft_max.... files. Then go to second step:
2. Second, this https://github.com/ICLab4DL/GGN/blob/main/eeg_main.py contains the feature composition steps (line 543). You just set args.task == 'generate_data', check the function: generate_tuh_data, you can set a proper time length or default.

Details refer to the suplementary:

https://static-content.springer.com/esm/art%3A10.1038%2Fs41598-022-23656-1/MediaObjects/41598_2022_23656_MOESM1_ESM.pdf
