### ISSUE TITLE
About update_A(self, mu, sig, pi) function

### ISSUE THREAD

**Issue by snowsj** [ICLab4DL/GGN#3]
**S = mu_k + n*sig_k** (line 324 in th gnn.py), Is this operation to obtain the updated probability distribution of node connections? Is my understanding incorrect? Why do we need to operate like this? And **Sim=torch. einsum ('bnc, bcm ->bnm ', S, S. transfer (2,1))**, what is this calculated for? 
Thank you for your answer！

**Comment by zhengdaoli** [comment]
i-th row of S is a random vector of node i, P is the "probability distribution of node connections"
